controllers/CalculationsController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\controllers;

use app\models\Data;
use yii\web\Controller;
use app\models\Coefficients;
use app\models\SelfEvaluation;
use yii\helpers\ArrayHelper;
use yii\data\ArrayDataProvider;
use app\models\Evaluation;
use app\models\EstimatesIntersection;

/**
 * Description of CalculationsController
 *
 * @author mezinn
 */
class CalculationsController extends Controller {

    public function actionIndex() {

        $data = Data::find()->all();





        $dataProvider = new ArrayDataProvider([
            'allModels' => $data
        ]);

        return $this->render('index', compact('dataProvider'));
    }

}

controllers/CoefficientsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Coefficients;
use app\models\search\SearchCoefficients;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CoefficientsController implements the CRUD actions for Coefficients model.
 */
class CoefficientsController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Coefficients models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new SearchCoefficients();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Coefficients model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Coefficients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Coefficients();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Coefficients model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Coefficients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Coefficients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Coefficients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Coefficients::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/DataController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Data;
use yii\web\Controller;
use app\models\Evaluation;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use app\models\Coefficients;
use app\models\SelfEvaluation;
use yii\data\ArrayDataProvider;
use app\models\search\SearchData;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;

/**
 * DataController implements the CRUD actions for Data model.
 */
class DataController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Data models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new SearchData();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Data model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Data model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Data();

        $evaluations = ArrayHelper::getColumn(Coefficients::find()->all(), function() {
                    return new Evaluation(['data_id' => Data::find()->max('id') + 1]);
                });
        $selfEvaluations = ArrayHelper::getColumn(Coefficients::find()->all(), function() {
                    return new SelfEvaluation(['data_id' => Data::find()->max('id') + 1]);
                });

        $evaluationDataProvider = new ArrayDataProvider([
            'allModels' => $evaluations,
        ]);

        $selfEvaluationDataProvider = new ArrayDataProvider([
            'allModels' => $selfEvaluations,
        ]);

        if ($model->load(Yii::$app->request->post()) &&
                $model->validate() &&
                Evaluation::loadMultiple($evaluations, Yii::$app->request->post()) &&
                Evaluation::validateMultiple($evaluations) &&
                SelfEvaluation::loadMultiple($selfEvaluations, Yii::$app->request->post()) &&
                SelfEvaluation::validateMultiple($selfEvaluations)) {
            $model->save();
            foreach ($evaluations as $evaluation) {
                $evaluation->save();
            }
            foreach ($selfEvaluations as $evaluation) {
                $evaluation->save();
            }
            return $this->redirect(['index']);
        }
        return $this->render('create', compact('model', 'evaluationDataProvider', 'selfEvaluationDataProvider'));
    }

    /**
     * Updates an existing Data model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        $coeffCount = Coefficients::find()->count();
        $evaluations = Evaluation::find()->where(['data_id' => $model->id])->all();
        $selfEvaluations = SelfEvaluation::find()->where(['data_id' => $model->id])->all();
        for ($i = count($evaluations); $i < $coeffCount; $i++) {
            array_push($evaluations, new Evaluation(['data_id' => $model->id]));
        }

        for ($i = count($selfEvaluations); $i < $coeffCount; $i++) {
            array_push($selfEvaluations, new SelfEvaluation(['data_id' => $model->id]));
        }


        $evaluationDataProvider = new ArrayDataProvider([
            'allModels' => $evaluations,
        ]);
        $selfEvaluationDataProvider = new ArrayDataProvider([
            'allModels' => $selfEvaluations,
        ]);

        if ($model->load(Yii::$app->request->post()) &&
                $model->validate() &&
                Evaluation::loadMultiple($evaluations, Yii::$app->request->post()) &&
                Evaluation::validateMultiple($evaluations) &&
                SelfEvaluation::loadMultiple($selfEvaluations, Yii::$app->request->post()) &&
                SelfEvaluation::validateMultiple($selfEvaluations)) {
            $model->save();
            foreach ($evaluations as $evaluation) {
                $evaluation->save();
            }
            foreach ($selfEvaluations as $evaluation) {
                $evaluation->save();
            }
            return $this->redirect(['index']);
        }
        return $this->render('update', compact('model', 'evaluationDataProvider', 'selfEvaluationDataProvider'));
    }

    /**
     * Deletes an existing Data model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Data model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Data the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Data::findOne($id)) !== null) {
            $coeffCount = (Coefficients::find()->count()) - 1;
            Evaluation::deleteAll("internal_index > $coeffCount");
            SelfEvaluation::deleteAll("internal_index > $coeffCount");
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/FurnituresController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Furnitures;
use app\models\search\SearchFurnitures;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FurnituresController implements the CRUD actions for Furnitures model.
 */
class FurnituresController extends Controller
{
    public $layout = 'furnitures';
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Furnitures models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchFurnitures();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Furnitures model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Furnitures();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Furnitures model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Furnitures model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Furnitures model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Furnitures the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Furnitures::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/furnitures.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-left'],
                'items' => [
                    ['label' => 'Меблі', 'url' => ['/furnitures/index']],
                    ['label' => 'Типи', 'url' => ['/furnitures-type/index']],
                ],
            ]);
            NavBar::end();
            ?>

            <div class="container">
                
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">

        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-left'],
                'items' => [
                    ['label' => 'Коефіцієнти', 'url' => ['/coefficients/index']],
                    ['label' => 'Дані', 'url' => ['/data/index']],
                    ['label' => 'Статистита зрізу', 'url' => ['/calculations/index']],
                ],
            ]);
            NavBar::end();
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">

        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>